# Generated by Django 3.0.5 on 2020-06-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200624_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='genre',
            new_name='skill',
        ),
    ]
