# Generated by Django 3.0.7 on 2020-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200624_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='skill',
            field=models.CharField(choices=[('Job Posting', 'Job Posting'), ('Help Wanted', 'Help wanted'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JavaScript'), ('UX', 'UX Design'), ('Node', 'Node.JS'), ('SQL', 'SQL'), ('PI', 'Project Ideas')], default='Job Posting', max_length=11),
        ),
    ]
