# Generated by Django 3.0.7 on 2020-06-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
